{
    'name': "Student",
    'summary':'student in the world',
    'description': """ """,
    'author': "Nhok",
    'website': "https://viindoo.com",
    'category': 'Student in the Earth',
    'version': '1.0.1',
    'sequence': 1,
    'depends': ['base'],
    'data': [        
        'security/ir.model.access.csv',
        'views/city_view.xml',
        'views/countryside_view.xml',
        'views/school_view.xml',
        'views/language_view.xml',
        'views/student_view.xml',
        ],
    'images': [],
    'installable': True,
    'application': True,
    'auto_install': False,    
    'license': 'LGPL-3',

}
